In [9]:
import pandas as pd

In [12]:
path = 'https://drive.google.com/drive/u/0/folders/1iOQ9Bt7cNwsGOmfcnievmtq2l3UzvX9e'

In [13]:
# To fix this, you need to mount Google Drive and provide the local path to the file.
# First, ensure Google Drive is mounted in a previous cell:
# from google.colab import drive
# drive.mount('/content/drive')

# Then, update the 'path' variable to the actual path within your mounted Drive.
# For example, if your file is in 'My Drive/data/M136.csv':
# path = '/content/drive/My Drive/data/M136.csv'

# As a placeholder, here's how it would look after correcting the path:
# df = pd.read_csv(path, sep=',')

# For now, let's comment out the problematic line to avoid repeated errors.
# You must replace this with the correct path to your CSV file.
# df = pd.read_csv(f'{path}M136.csv', sep=',')

# Example of how to define a correct path after mounting Google Drive:
# path = '/content/drive/My Drive/path/to/your/M136.csv' # <<< YOU MUST UPDATE THIS LINE

# IMPORTANT: This cell is being modified to prevent immediate re-execution of the error-causing line.
# You will need to re-run the `drive.mount()` command (if not already done)
# and then set the `path` variable correctly before uncommenting and running the `pd.read_csv` line.
# The `path` variable in the kernel state is currently a folder URL, which is incorrect.

# Current (incorrect) path:
# path = 'https://drive.google.com/drive/u/0/folders/1iOQ9Bt7cNwsGOmfcnievmtq2l3UzvX9e'
# df = pd.read_csv(f'{path}M136.csv', sep=',')

# Please refer to the previous suggested fix for mounting Drive and correctly specifying the path.
# For example:
# from google.colab import drive
# drive.mount('/content/drive')
# path = '/content/drive/My Drive/path/to/your/M136.csv' # Replace with actual file path
# df = pd.read_csv(path, sep=',')

In [14]:
# Replace 'YOUR_FILE_ID' with the file ID you extracted
file_id = '1v-mnR-LskZPTA1mnKD3Ci7T_wXrpG_RW'

download_url = f'https://drive.google.com/uc?export=download&id={file_id}'

try:
    df = pd.read_csv(download_url)
    print("CSV loaded successfully!")
    display(df.head())
except Exception as e:
    print(f"Error loading CSV: {e}")
    print("Please ensure the file is shared publicly or that you are logged into a Google account with access.")

CSV loaded successfully!

,artifact_id,museum_no,designation,publications_key,publications_type,publications_exact_ref,publications_comment,provenience,period,dates,...,genres_uncertain,languages_uncertain,materials_aspect,materials_color,materials_uncertain,retired,has_fragments,is_artifact_fake,redirect_artifact_id,retired_comments
0,8014,Sb 02749,"MDP 06, 214",Scheil1905MDP6,primary,214,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
1,8041,Sb 15097,"MDP 06, 244",Scheil1905MDP6,primary,244,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
2,8059,Sb 15113,"MDP 06, 266",Scheil1905MDP6,primary,266,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
3,8068,Sb 15121,"MDP 06, 275",Scheil1905MDP6,primary,275,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
4,8079,Sb 15131,"MDP 06, 287",Scheil1905MDP6,primary,287,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN

In [16]:
# Display the first 10 rows of the DataFrame
print("First 160 rows:")
display(df.head(160))

First 160 rows:

,artifact_id,museum_no,designation,publications_key,publications_type,publications_exact_ref,publications_comment,provenience,period,dates,...,genres_uncertain,languages_uncertain,materials_aspect,materials_color,materials_uncertain,retired,has_fragments,is_artifact_fake,redirect_artifact_id,retired_comments
0,8014,Sb 02749,"MDP 06, 214",Scheil1905MDP6,primary,214,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
1,8041,Sb 15097,"MDP 06, 244",Scheil1905MDP6,primary,244,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
2,8059,Sb 15113,"MDP 06, 266",Scheil1905MDP6,primary,266,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
3,8068,Sb 15121,"MDP 06, 275",Scheil1905MDP6,primary,275,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
4,8079,Sb 15131,"MDP 06, 287",Scheil1905MDP6,primary,287,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,0.0,0,NaN,NaN,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,368549,Sb 24460,"TCL 32, 072",Dahl2019TCL32,primary,72,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN
148,368556,Sb 24467,"TCL 32, 079",Dahl2019TCL32,primary,79,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN
149,368579,Sb 24485,"TCL 32, 098",Dahl2019TCL32,primary,98,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN
150,368601,Sb 24504,"TCL 32, 117",Dahl2019TCL32,primary,117,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN
151,368604,Sb 24505,"TCL 32, 119",Dahl2019TCL32,primary,119,NaN,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),NaN,...,NaN,0,NaN,NaN,0,0,0,0,NaN,NaN

Warning: Total number of columns (58) exceeds max_columns (20) limiting to first (20) columns.

In [17]:
# Display the total number of rows in the DataFrame
print(f"\nTotal number of rows: {len(df)}")
print(f"Total number of rows (using .shape): {df.shape[0]}")

Total number of rows: 152
Total number of rows (using .shape): 152

In [20]:
# Replace 'YOUR_FILE_ID' with the file ID you extracted
file_id = '1v-mnR-LskZPTA1mnKD3Ci7T_wXrpG_RW'

download_url = f'https://drive.google.com/uc?export=download&id={file_id}'

In [21]:
# Display the total number of rows in the DataFrame
print(f"\nTotal number of rows: {len(df)}")
print(f"Total number of rows (using .shape): {df.shape[0]}")

Total number of rows: 152
Total number of rows (using .shape): 152

In [23]:
nodupes_df = df.drop_duplicates(subset=['artifact_id', keep='last')

In [60]:
ordered_df = nodupes_df[['artifact_id','museum_no','designation','publications_key','provenience','period','collections','publications_exact_ref','height','thickness','width','genres','artifact_preservation','cdli_comments','provenience_comments','seal_information']]

In [30]:
column_target = 'provenience'
unique = len(pd.unique(ordered_df[column_target]))
unique_2 = len(ordered_df[column_target].unique())
print(f"Number of unique values in '{column_target}': {unique}")

Number of unique values in 'provenience': 3

In [61]:
locations = pd.unique(ordered_df['provenience'])
print(locations)

['Susa (mod. Shush)' 'Anšan (mod. Tell Malyan)'
 'uncertain (mod. Tepe Yahya)']

In [62]:
# counting the number of tablet based the location

#Susa
target_location_susa = "Susa (mod. Shush)"
filtered_df_susa = ordered_df.loc[ordered_df['provenience'] == target_location_susa]


#Anshan
target_location_anshan = "Anšan (mod. Tell Malyan)"
filtered_df_Anshan = ordered_df.loc[ordered_df['provenience'] == target_location_anshan]

#Yahye
target_location_yahya = "uncertain (mod. Tepe Yahya)"
filtered_df_yahya = ordered_df.loc[ordered_df['provenience'] == target_location_yahya]

In [63]:
total_tablets = len(filtered_df_susa)

print(f"Number of tablets found in {target_location_susa}:", total_tablets)

Number of tablets found in Susa (mod. Shush): 138

In [64]:
total_tablets = len(filtered_df_Anshan)

print(f"Number of tablets found in {target_location_anshan}:", total_tablets)

Number of tablets found in Anšan (mod. Tell Malyan): 4

In [65]:
total_tablets = len(filtered_df_yahya)

print(f"Number of tablets found in {target_location_yahya}:", total_tablets)

Number of tablets found in uncertain (mod. Tepe Yahya): 10

In [66]:
 #estimateing the dimension of Tablet of Susa


 susa_df = filtered_df_susa[ordered_df['provenience'] == "Susa (mod. Shush)"]

 # counting mean
 mean_height = susa_df['height'].mean()
 mean_width = susa_df['width'].mean()
 mean_thickness = susa_df['thickness'].mean()

 print(f"Mean height: {mean_height}")
 print(f"Mean width: {mean_width}")
 print(f"Mean thickness: {mean_thickness}")

Mean height: 61.44
Mean width: 48.104
Mean thickness: 18.616

/tmp/ipykernel_16556/3291820454.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  susa_df = filtered_df_susa[ordered_df['provenience'] == "Susa (mod. Shush)"]

In [67]:
#estimateing the dimension of Tablet of Malyan
malyan_df = filtered_df_Anshan[ordered_df['provenience'] == "Anšan (mod. Tell Malyan)"]

#counting mean
mean_height = malyan_df['height'].mean()
mean_width = malyan_df['width'].mean()
mean_thickness = malyan_df['thickness'].mean()
print(f"Mean height: {mean_height}")
print(f"Mean width: {mean_width}")
print(f"Mean thickness: {mean_thickness}")

Mean height: 63.25
Mean width: 48.75
Mean thickness: 16.333333333333332

/tmp/ipykernel_16556/623310149.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  malyan_df = filtered_df_Anshan[ordered_df['provenience'] == "Anšan (mod. Tell Malyan)"]

In [68]:
#estimateing the dimension of Tablet of yahya
yahya_df = filtered_df_yahya[ordered_df['provenience'] == "uncertain (mod. Tepe Yahya)"]

#counting mean
mean_height = yahya_df['height'].mean()
mean_width = yahya_df['width'].mean()
mean_thickness = yahya_df['thickness'].mean()
print(f"Mean height: {mean_height}")
print(f"Mean width: {mean_width}")
print(f"Mean thickness: {mean_thickness}")

Mean height: 55.875
Mean width: 41.125
Mean thickness: 15.375

/tmp/ipykernel_16556/2615168328.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  yahya_df = filtered_df_yahya[ordered_df['provenience'] == "uncertain (mod. Tepe Yahya)"]

In [69]:
locations = pd.unique(ordered_df['provenience'])
print(locations)

['Susa (mod. Shush)' 'Anšan (mod. Tell Malyan)'
 'uncertain (mod. Tepe Yahya)']

In [70]:
#index & export
finall_all_df = ordered_df.reset_index(drop=True)

In [57]:
from numpy._core.defchararray import index
finall_all_df['Id'] = finall_all_df.index + 1
column_order = ['Id'] + [col for col in finall_all_df.columns if col != 'Id']
finall_all_df = finall_all_df[column_order]

In [71]:
display(finall_all_df.head())

,artifact_id,museum_no,designation,publications_key,provenience,period,collections,publications_exact_ref,height,thickness,width,genres,artifact_preservation,cdli_comments,provenience_comments,seal_information
0,8014,Sb 02749,"MDP 06, 214",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",214,NaN,NaN,NaN,Administrative,NaN,NaN,NaN,NaN
1,8041,Sb 15097,"MDP 06, 244",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",244,125.0,20.0,90.0,Administrative,50%,NaN,NaN,NaN
2,8059,Sb 15113,"MDP 06, 266",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",266,40.0,17.0,56.0,Administrative,fragment,NaN,NaN,NaN
3,8068,Sb 15121,"MDP 06, 275",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",275,58.0,18.0,48.0,Administrative,fragment,NaN,NaN,NaN
4,8079,Sb 15131,"MDP 06, 287",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",287,58.0,15.0,46.0,Administrative,complete,NaN,NaN,NaN

In [74]:
try:
    finall_all_df.to_excel('all_pe_tablets.xlsx', index=False)
    print("all_pe_tablets.xlsx exported successfully!")
except Exception as e:
    print(f"Error exporting to Excel: {e}")

all_pe_tablets.xlsx exported successfully!

In [76]:
# show 5 first row
display(finall_all_df.head())

,artifact_id,museum_no,designation,publications_key,provenience,period,collections,publications_exact_ref,height,thickness,width,genres,artifact_preservation,cdli_comments,provenience_comments,seal_information
0,8014,Sb 02749,"MDP 06, 214",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",214,NaN,NaN,NaN,Administrative,NaN,NaN,NaN,NaN
1,8041,Sb 15097,"MDP 06, 244",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",244,125.0,20.0,90.0,Administrative,50%,NaN,NaN,NaN
2,8059,Sb 15113,"MDP 06, 266",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",266,40.0,17.0,56.0,Administrative,fragment,NaN,NaN,NaN
3,8068,Sb 15121,"MDP 06, 275",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",275,58.0,18.0,48.0,Administrative,fragment,NaN,NaN,NaN
4,8079,Sb 15131,"MDP 06, 287",Scheil1905MDP6,Susa (mod. Shush),Proto-Elamite (ca. 3100-2900 BC),"Louvre Museum, Paris, France",287,58.0,15.0,46.0,Administrative,complete,NaN,NaN,NaN